CREATE TABLE DOG (
    DOG_ID            INTEGER(22) PRIMARY KEY,
    NAME              VARCHAR2(30),
    DATE_OF_BIRTH     TIMESTAMP(3) DEFAULT SYSDATE,
    HEIGHT            DOUBLE,
    WEIGHT            DOUBLE
);