INSERT INTO DOG (DOG_ID, NAME, HEIGHT, WEIGHT) VALUES (1, 'name 1', 1, 1);
INSERT INTO DOG (DOG_ID, NAME, HEIGHT, WEIGHT) VALUES (2, 'name 2', 2, 2);
INSERT INTO DOG (DOG_ID, NAME, HEIGHT, WEIGHT) VALUES (3, 'name 3', 3, 3);